default:
  image: osrf/ros:iron-desktop-full
  tags:
    - ci.inria.fr
    - large
    - linux

stages:
  - build-and-test
  - release

build-and-test-job:
  stage: build-and-test
  script:
    - apt-get update -y
    - apt-get install -y swig curl ros-iron-tf2 ros-iron-grid-map
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install
    - poetry run poe all_checks

pages:
  stage: build-and-test
  script:
    - apt-get update -y
    - apt-get install -y swig curl ros-iron-tf2 ros-iron-grid-map
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install
    - cd docs
    - poetry run make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - main

release:
  stage: release
  variables:
    GL_TOKEN: $GL_TOKEN
  script:
    - apt-get update -y
    - apt-get install -y swig curl ros-iron-tf2 ros-iron-grid-map
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install
    - poetry run semantic-release version
    - poetry run semantic-release publish
  only:
    - main
