default:
  image: osrf/ros:humble-desktop-full
  tags:
    - ci.inria.fr
    - large
    - linux

stages:
  - build-and-test
  - release

build-and-test-job:
  stage: build-and-test
  script:
    - apt-get update -y
    - apt-get install -y swig curl python3-pip
    - rosdep install --from-paths . -r -y
    - pip install -r namosim/requirements.txt
    - pip install -r namoros/requirements.txt
    - ./scripts/test_all.sh
  except:
    - tags

pages:
  stage: build-and-test
  script:
    - apt-get update -y
    - apt-get install -y swig curl python3-pip
    - rosdep install --from-paths . -r -y
    - pip install -r namosim/requirements.txt
    - pip install -r namoros/requirements.txt
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - main
    - dev
  except:
    - tags
