default:
  image: osrf/ros:humble-desktop-full
  tags:
    - ci.inria.fr
    - large
    - linux

stages:
  - build-and-test
  - release

build-and-test-job:
  stage: build-and-test
  script:
    - apt-get update -y
    - apt-get install -y swig curl ros-humble-tf2 ros-humble-grid-map python3-pip
    - pip install -r requirements.txt
    - ./scripts/test_all.sh
  except:
    - tags

pages:
  stage: build-and-test
  script:
    - apt-get update -y
    - apt-get install -y swig curl ros-humble-tf2 ros-humble-grid-map python3-pip
    - pip install -r requirements.txt
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - main
    - dev
  except:
    - tags
